# Generated by Django 4.1.2 on 2022-11-08 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='nombre',
            new_name='ids',
        ),
    ]
