# Generated by Django 4.1.2 on 2022-10-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('importe', models.FloatField()),
                ('unidades', models.IntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modelo', to='tienda.producto', to_field='modelo')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nombre', to='tienda.producto', to_field='nombre')),
            ],
        ),
    ]
