# Generated by Django 4.1.2 on 2022-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_nombre_compra_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='ids',
            new_name='producto',
        ),
    ]
