# Generated by Django 4.1.2 on 2022-10-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_modelo_alter_producto_nombre_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
