# Generated by Django 4.1.2 on 2022-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_ids_compra_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
