# Generated by Django 4.1.2 on 2022-11-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
