# Generated by Django 4.1.2 on 2022-11-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_compra_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id', to='tienda.producto'),
        ),
    ]
